FROM node:26-alpine

# Install curl untuk healthcheck
RUN apk add --no-cache curl

USER node
WORKDIR /home/node/app

COPY --chown=node:node package*.json ./
RUN npm ci --omit=dev

COPY --chown=node:node prisma.config.js ./
COPY --chown=node:node prisma ./prisma

RUN npx prisma generate

COPY --chown=node:node . .

CMD ["npm", "run", "start"]